services:
  dev-server:
    image: nginx:1.27.3
    ports:
      - "8080:80"
    volumes:
      - ./lib/:/usr/share/nginx/html/lib/
      - ./src/:/usr/share/nginx/html/src/
      - ./index.html:/usr/share/nginx/html/index.html
      - ./dev.nginx.conf:/etc/nginx/conf.d/default.conf